name: render
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: system deps
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      - name: run tests & build
        run: |
          R -e "renv::restore(); testthat::test_dir('tests'); targets::tar_make()"
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: report.pdf
